# 数据库
db:
  driver: mysql
  addr: root:123456@tcp(127.0.0.1:3306)/qasystem?charset=utf8&parseTime=True&loc=Local

# Redis
redis:
  addr: 127.0.0.1:6379
  password:
  db: 0

# jwt认证密钥
jwtKey: jwt123456

# 端口
address: :8080