# 数据库
db:
  driver: mysql
  addr: root:root1234@tcp(mysql8019:3306)/qasystem?charset=utf8&parseTime=True&loc=Local

# Redis
redis:
  addr: redis-db:6379
  password:
  db: 0

# jwt认证密钥
jwtKey: jwt123456

# 端口
address: :8080